/// <reference path="../.astro/types.d.ts" />
MICROCMS_SERVICE_DOMAIN=kanyukai
MICROCMS_API_KEY=X7LVuT4hgwBBpkAJTHvCDF5CYfWrMXW5xYjx

MICROCMS_SERVICE_DOMAIN2=kanyukai1953
MICROCMS_API_KEY2="2CvovwVEy1HmAwAl8lqsauRI45uVs3NFbtDx"